language: php
dist: trusty

php:
  - 7.3
  - 7.4
  - hhvm
  - nightly

before_script:
  - composer install

script:
  - vendor/bin/phpunit tests

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: nightly
